########################
# HTTP server settings #
########################
port: 9090
max_payload_size_bytes: 41943040
cors_allow_origins: ["*"]

####################
# General settings #
####################
persist_path: "./chroma"
allow_reset: false # defaults to false
sqlitedb:
  hash_type: "md5" # or "sha256"
  migration_mode: "apply" # or "validate"
sysdb:
  sqlite:
    log_topic_namespace: "default"
    log_tenant: "default"
help: "chroma run chromaconfig.yaml"